
# Creacion tabla regiones
CREATE TABLE `formulariophp`.`regiones` (`id_reg` INT(3) NOT NULL , `nom_reg` VARCHAR(200) NOT NULL , PRIMARY KEY (`id_reg`)) ENGINE = InnoDB;

# Poblado tabla regiones
INSERT INTO `regiones` (`id_reg`, `nom_reg`) VALUES
('15','Arica y Parinacota'),
('1','Tarapacá'),
('2','Antofagasta'),
('3','Atacama'),
('4','Coquimbo'),
('5','Valparaíso'),
('13','Metropolitana de Santiago'),
('6','Libertador Gral. Bernardo O’Higgins'),
('7','Maule'),
('16','Ñuble'),
('8','Biobío'),
('9','Araucanía'),
('14','Los Ríos'),
('10','Los Lagos'),
('11','Aisén del Gral. Carlos Ibáñez del Campo'),
('12','Magallanes y de la Antártica Chilena');

# Creacion tabla comunas
CREATE TABLE `formulariophp`.`comunas` (`id_com` INT(4) NOT NULL AUTO_INCREMENT, `nom_com` VARCHAR(200) NOT NULL , `fk_reg` INT(3) NOT NULL , PRIMARY KEY (`id_com`)) ENGINE = InnoDB;
# agregar foreing key 
ALTER TABLE `comunas` ADD CONSTRAINT `fk_id_reg` FOREIGN KEY (`fk_reg`) REFERENCES `regiones`(`id_reg`) ON DELETE CASCADE ON UPDATE CASCADE;
# Poblado de tabla comuna
INSERT INTO `comunas` (`id_com`,`nom_com`, `fk_reg`) VALUES
(NULL, 'Arica','15'),
(NULL, 'Camarones','15'),
(NULL, 'General Lagos','15'),
(NULL, 'Putre','15'),
(NULL, 'Alto Hospicio','1'),
(NULL, 'Camiña','1'),
(NULL, 'Colchane','1'),
(NULL, 'Huara','1'),
(NULL, 'Iquique','1'),
(NULL, 'Pica','1'),
(NULL, 'Pozo Almonte','1'),
(NULL, 'Antofagasta','2'),
(NULL, 'Calama','2'),
(NULL, 'María Elena','2'),
(NULL, 'Mejillones','2'),
(NULL, 'Ollagüe','2'),
(NULL, 'San Pedro de Atacama','2'),
(NULL, 'Sierra Gorda','2'),
(NULL, 'Taltal','2'),
(NULL, 'Tocopilla','2'),
(NULL, 'Alto del Carmen','3'),
(NULL, 'Caldera','3'),
(NULL, 'Chañaral','3'),
(NULL, 'Copiapó','3'),
(NULL, 'Diego de Almagro','3'),
(NULL, 'Freirina','3'),
(NULL, 'Huasco','3'),
(NULL, 'Tierra Amarilla','3'),
(NULL, 'Vallenar','3'),
(NULL, 'Andacollo','4'),
(NULL, 'Canela','4'),
(NULL, 'Combarbalá','4'),
(NULL, 'Coquimbo','4'),
(NULL, 'Illapel','4'),
(NULL, 'La Higuera','4'),
(NULL, 'La Serena','4'),
(NULL, 'Los Vilos','4'),
(NULL, 'Monte Patria','4'),
(NULL, 'Ovalle','4'),
(NULL, 'Paiguano','4'),
(NULL, 'Punitaqui','4'),
(NULL, 'Río Hurtado','4'),
(NULL, 'Salamanca','4'),
(NULL, 'Vicuña','4'),
(NULL, 'Algarrobo','5'),
(NULL, 'Cabildo','5'),
(NULL, 'Calera','5'),
(NULL, 'Calle Larga','5'),
(NULL, 'Cartagena','5'),
(NULL, 'Casablanca','5'),
(NULL, 'Catemu','5'),
(NULL, 'Concón','5'),
(NULL, 'El Quisco','5'),
(NULL, 'El Tabo','5'),
(NULL, 'Hijuelas','5'),
(NULL, 'Isla de Pascua','5'),
(NULL, 'Juan Fernández','5'),
(NULL, 'La Cruz','5'),
(NULL, 'La Ligua','5'),
(NULL, 'Limache','5'),
(NULL, 'Llaillay','5'),
(NULL, 'Los Andes','5'),
(NULL, 'Nogales','5'),
(NULL, 'Olmué','5'),
(NULL, 'Panquehue','5'),
(NULL, 'Papudo','5'),
(NULL, 'Petorca','5'),
(NULL, 'Puchuncaví','5'),
(NULL, 'Putaendo','5'),
(NULL, 'Quillota','5'),
(NULL, 'Quilpué','5'),
(NULL, 'Quintero','5'),
(NULL, 'Rinconada','5'),
(NULL, 'San Antonio','5'),
(NULL, 'San Esteban','5'),
(NULL, 'San Felipe','5'),
(NULL, 'Santa María','5'),
(NULL, 'Santo Domingo','5'),
(NULL, 'Valparaíso','5'),
(NULL, 'Villa Alemana','5'),
(NULL, 'Viña del Mar','5'),
(NULL, 'Zapallar','5'),
(NULL, 'Alhué','13'),
(NULL, 'Buin','13'),
(NULL, 'Calera de Tango','13'),
(NULL, 'Cerrillos','13'),
(NULL, 'Cerro Navia','13'),
(NULL, 'Colina','13'),
(NULL, 'Conchalí','13'),
(NULL, 'Curacaví','13'),
(NULL, 'El Bosque','13'),
(NULL, 'El Monte','13'),
(NULL, 'Estación Central','13'),
(NULL, 'Huechuraba','13'),
(NULL, 'Independencia','13'),
(NULL, 'Isla de Maipo','13'),
(NULL, 'La Cisterna','13'),
(NULL, 'La Florida','13'),
(NULL, 'La Granja','13'),
(NULL, 'La Pintana','13'),
(NULL, 'La Reina','13'),
(NULL, 'Lampa','13'),
(NULL, 'Las Condes','13'),
(NULL, 'Lo Barnechea','13'),
(NULL, 'Lo Espejo','13'),
(NULL, 'Lo Prado','13'),
(NULL, 'Macul','13'),
(NULL, 'Maipú','13'),
(NULL, 'María Pinto','13'),
(NULL, 'Melipilla','13'),
(NULL, 'Ñuñoa','13'),
(NULL, 'Padre Hurtado','13'),
(NULL, 'Paine','13'),
(NULL, 'Pedro Aguirre Cerda','13'),
(NULL, 'Peñaflor','13'),
(NULL, 'Peñalolén','13'),
(NULL, 'Pirque','13'),
(NULL, 'Providencia','13'),
(NULL, 'Pudahuel','13'),
(NULL, 'Puente Alto','13'),
(NULL, 'Quilicura','13'),
(NULL, 'Quinta Normal','13'),
(NULL, 'Recoleta','13'),
(NULL, 'Renca','13'),
(NULL, 'San Bernardo','13'),
(NULL, 'San Joaquín','13'),
(NULL, 'San José de Maipo','13'),
(NULL, 'San Miguel','13'),
(NULL, 'San Pedro','13'),
(NULL, 'San Ramón','13'),
(NULL, 'Santiago','13'),
(NULL, 'Talagante','13'),
(NULL, 'Tiltil','13'),
(NULL, 'Vitacura','13'),
(NULL, 'Chimbarongo','6'),
(NULL, 'Chépica','6'),
(NULL, 'Codegua','6'),
(NULL, 'Coinco','6'),
(NULL, 'Coltauco','6'),
(NULL, 'Doñihue','6'),
(NULL, 'Graneros','6'),
(NULL, 'La Estrella','6'),
(NULL, 'Las Cabras','6'),
(NULL, 'Litueche','6'),
(NULL, 'Lolol','6'),
(NULL, 'Machalí','6'),
(NULL, 'Malloa','6'),
(NULL, 'Marchihue','6'),
(NULL, 'Nancagua','6'),
(NULL, 'Navidad','6'),
(NULL, 'Olivar','6'),
(NULL, 'Palmilla','6'),
(NULL, 'Paredones','6'),
(NULL, 'Peralillo','6'),
(NULL, 'Peumo','6'),
(NULL, 'Pichidegua','6'),
(NULL, 'Pichilemu','6'),
(NULL, 'Placilla','6'),
(NULL, 'Pumanque','6'),
(NULL, 'Quinta de Tilcoco','6'),
(NULL, 'Rancagua','6'),
(NULL, 'Rengo','6'),
(NULL, 'Requínoa','6'),
(NULL, 'San Fernando','6'),
(NULL, 'San Francisco de Mostazal','6'),
(NULL, 'San Vicente de Tagua Tagua','6'),
(NULL, 'Santa Cruz','6'),
(NULL, 'Cauquenes','7'),
(NULL, 'Chanco','7'),
(NULL, 'Colbún','7'),
(NULL, 'Constitución','7'),
(NULL, 'Curepto','7'),
(NULL, 'Curicó','7'),
(NULL, 'Empedrado','7'),
(NULL, 'Hualañé','7'),
(NULL, 'Licantén','7'),
(NULL, 'Linares','7'),
(NULL, 'Longaví','7'),
(NULL, 'Maule','7'),
(NULL, 'Molina','7'),
(NULL, 'Parral','7'),
(NULL, 'Pelarco','7'),
(NULL, 'Pelluhue','7'),
(NULL, 'Pencahue','7'),
(NULL, 'Rauco','7'),
(NULL, 'Retiro','7'),
(NULL, 'Romeral','7'),
(NULL, 'Río Claro','7'),
(NULL, 'Sagrada Familia','7'),
(NULL, 'San Clemente','7'),
(NULL, 'San Javier de Loncomilla','7'),
(NULL, 'San Rafael','7'),
(NULL, 'Talca','7'),
(NULL, 'Teno','7'),
(NULL, 'Vichuquén','7'),
(NULL, 'Villa Alegre','7'),
(NULL, 'Yerbas Buenas','7'),
(NULL, 'Bulnes','16'),
(NULL, 'Chillán Viejo','16'),
(NULL, 'Chillán','16'),
(NULL, 'Cobquecura','16'),
(NULL, 'Coelemu','16'),
(NULL, 'Coihueco','16'),
(NULL, 'El Carmen','16'),
(NULL, 'Ninhue','16'),
(NULL, 'Ñiquén','16'),
(NULL, 'Pemuco','16'),
(NULL, 'Pinto','16'),
(NULL, 'Portezuelo','16'),
(NULL, 'Quillón','16'),
(NULL, 'Quirihue','16'),
(NULL, 'Ránquil','16'),
(NULL, 'San Carlos','16'),
(NULL, 'San Fabián','16'),
(NULL, 'San Ignacio','16'),
(NULL, 'San Nicolás','16'),
(NULL, 'Treguaco','16'),
(NULL, 'Yungay','16'),
(NULL, 'Alto Biobío','8'),
(NULL, 'Antuco','8'),
(NULL, 'Arauco','8'),
(NULL, 'Cabrero','8'),
(NULL, 'Cañete','8'),
(NULL, 'Chiguayante','8'),
(NULL, 'Concepción','8'),
(NULL, 'Contulmo','8'),
(NULL, 'Coronel','8'),
(NULL, 'Curanilahue','8'),
(NULL, 'Florida','8'),
(NULL, 'Hualpén','8'),
(NULL, 'Hualqui','8'),
(NULL, 'Laja','8'),
(NULL, 'Lebu','8'),
(NULL, 'Los Álamos','8'),
(NULL, 'Los Ángeles','8'),
(NULL, 'Lota','8'),
(NULL, 'Mulchén','8'),
(NULL, 'Nacimiento','8'),
(NULL, 'Negrete','8'),
(NULL, 'Penco','8'),
(NULL, 'Quilaco','8'),
(NULL, 'Quilleco','8'),
(NULL, 'San Pedro de la Paz','8'),
(NULL, 'San Rosendo','8'),
(NULL, 'Santa Bárbara','8'),
(NULL, 'Santa Juana','8'),
(NULL, 'Talcahuano','8'),
(NULL, 'Tirúa','8'),
(NULL, 'Tomé','8'),
(NULL, 'Tucapel','8'),
(NULL, 'Yumbel','8'),
(NULL, 'Angol','9'),
(NULL, 'Carahue','9'),
(NULL, 'Cholchol','9'),
(NULL, 'Collipulli','9'),
(NULL, 'Cunco','9'),
(NULL, 'Curacautín','9'),
(NULL, 'Curarrehue','9'),
(NULL, 'Ercilla','9'),
(NULL, 'Freire','9'),
(NULL, 'Galvarino','9'),
(NULL, 'Gorbea','9'),
(NULL, 'Lautaro','9'),
(NULL, 'Loncoche','9'),
(NULL, 'Lonquimay','9'),
(NULL, 'Los Sauces','9'),
(NULL, 'Lumaco','9'),
(NULL, 'Melipeuco','9'),
(NULL, 'Nueva Imperial','9'),
(NULL, 'Padre las Casas','9'),
(NULL, 'Perquenco','9'),
(NULL, 'Pitrufquén','9'),
(NULL, 'Pucón','9'),
(NULL, 'Purén','9'),
(NULL, 'Renaico','9'),
(NULL, 'Saavedra','9'),
(NULL, 'Temuco','9'),
(NULL, 'Teodoro Schmidt','9'),
(NULL, 'Toltén','9'),
(NULL, 'Traiguén','9'),
(NULL, 'Victoria','9'),
(NULL, 'Vilcún','9'),
(NULL, 'Villarrica','9'),
(NULL, 'Corral','14'),
(NULL, 'Futrono','14'),
(NULL, 'La Unión','14'),
(NULL, 'Lago Ranco','14'),
(NULL, 'Lanco','14'),
(NULL, 'Los Lagos','14'),
(NULL, 'Mariquina','14'),
(NULL, 'Máfil','14'),
(NULL, 'Paillaco','14'),
(NULL, 'Panguipulli','14'),
(NULL, 'Río Bueno','14'),
(NULL, 'Valdivia','14'),
(NULL, 'Ancud','10'),
(NULL, 'Calbuco','10'),
(NULL, 'Castro','10'),
(NULL, 'Chaitén','10'),
(NULL, 'Chonchi','10'),
(NULL, 'Cochamó','10'),
(NULL, 'Curaco de Vélez','10'),
(NULL, 'Dalcahue','10'),
(NULL, 'Fresia','10'),
(NULL, 'Frutillar','10'),
(NULL, 'Futaleufú','10'),
(NULL, 'Hualaihué','10'),
(NULL, 'Llanquihue','10'),
(NULL, 'Los Muermos','10'),
(NULL, 'Maullín','10'),
(NULL, 'Osorno','10'),
(NULL, 'Palena','10'),
(NULL, 'Puerto Montt','10'),
(NULL, 'Puerto Octay','10'),
(NULL, 'Puerto Varas','10'),
(NULL, 'Puqueldón','10'),
(NULL, 'Purranque','10'),
(NULL, 'Puyehue','10'),
(NULL, 'Queilén','10'),
(NULL, 'Quellón','10'),
(NULL, 'Quemchi','10'),
(NULL, 'Quinchao','10'),
(NULL, 'Río Negro','10'),
(NULL, 'San Juan de la Costa','10'),
(NULL, 'San Pablo','10'),
(NULL, 'Aisén','11'),
(NULL, 'Chile Chico','11'),
(NULL, 'Cisnes','11'),
(NULL, 'Cochrane','11'),
(NULL, 'Coyhaique','11'),
(NULL, 'Guaitecas','11'),
(NULL, 'Lago Verde','11'),
(NULL, 'O’Higgins','11'),
(NULL, 'Río Ibáñez','11'),
(NULL, 'Tortel','11'),
(NULL, 'Antártica','12'),
(NULL, 'Cabo de Hornos (Ex Navarino)','12'),
(NULL, 'Laguna Blanca','12'),
(NULL, 'Natales','12'),
(NULL, 'Porvenir','12'),
(NULL, 'Primavera','12'),
(NULL, 'Punta Arenas','12'),
(NULL, 'Río Verde','12'),
(NULL, 'San Gregorio','12'),
(NULL, 'Timaukel','12'),
(NULL, 'Torres del Paine','12');

